security:
    providers:
        main_provider:
            entity:
                class:    NantesBundle:Users
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main: # <-- nom du firewall
                    pattern: ^/
                    anonymous: ~
                    form_login:
                        login_path: login
                        check_path: login
                    logout:
                         path: logout
                         target: nantes_homepage

#         encoders:
#             MoviesBundle\Entity\Users:
#                 algorithm: bcrypt
#                 cost: 10
#
#             access_control:
#                 - { path: ^/admin, roles: ROLE_ADMIN }
#                 - { path: ^/events/ajout$, roles: ROLE_EVENT_PLANNER }
#
#             role_hierarchy:
#                 ROLE_ADMIN: ROLE_EVENT_PLANNER
#                 ROLE_EVENT_PLANNER: ROLE_USER